### ISSUE TITLE
An icon in the address bar

### ISSUE THREAD

**Issue by xkajxkajx** [dvingerh/yt-dl-protocol#1]
It would be better if we can add an icon in the address bar 

OR MUCH EASIER

to add a context menu on links.

P.S. I have used "Flagfox" add-on to add an item there and it works.

![Flagfox-Options](https://github.com/user-attachments/assets/7b4ef324-4045-4756-af12-653d82e5245d)

**Comment by dvingerh** [comment]
Your solution is okay, so I will pin it for those interested. However I prefer a bookmarklet because it's a built-in feature on every browser and the lack of an icon doesn't impact performance. An icon can't be added for the bookmarklet because it's derived from the bookmarked site's favicon (and not a bunch of JS code)
